# Generated by Django 6.1.1 on 2026-10-01 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptions", "0007_llminvocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionWorkflowRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_sha256", models.CharField(max_length=64)),
                ("versions", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(db_index=True, default="queued", max_length=24),
                ),
                ("lease_owner", models.UUIDField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_runs",
                        to="prescriptions.prescriptiondocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrescriptionWorkflowCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(blank=True, max_length=255)),
                ("checkpoint_id", models.CharField(max_length=64)),
                ("parent_checkpoint_id", models.CharField(blank=True, max_length=64)),
                ("payload_type", models.CharField(max_length=32)),
                ("payload", models.BinaryField()),
                ("metadata_type", models.CharField(max_length=32)),
                ("metadata", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="prescriptions.prescriptionworkflowrun",
                    ),
                ),
            ],
            options={
                "ordering": ("-checkpoint_id",),
            },
        ),
        migrations.CreateModel(
            name="PrescriptionWorkflowWrite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(blank=True, max_length=255)),
                ("checkpoint_id", models.CharField(max_length=64)),
                ("task_id", models.CharField(max_length=255)),
                ("task_path", models.TextField(blank=True)),
                ("write_index", models.IntegerField()),
                ("channel", models.CharField(max_length=255)),
                ("payload_type", models.CharField(max_length=32)),
                ("payload", models.BinaryField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_writes",
                        to="prescriptions.prescriptionworkflowrun",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="prescriptionworkflowcheckpoint",
            constraint=models.UniqueConstraint(
                fields=("run", "namespace", "checkpoint_id"),
                name="prescription_checkpoint_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="prescriptionworkflowwrite",
            constraint=models.UniqueConstraint(
                fields=("run", "namespace", "checkpoint_id", "task_id", "write_index"),
                name="prescription_pending_write_identity",
            ),
        ),
    ]
