# Generated by Django 6.1.1 on 2026-10-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptions", "0008_prescriptionworkflowrun_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionreview",
            name="approved_revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prescriptionreview",
            name="revision",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
