# Generated by Django 6.1.1 on 2026-10-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptions", "0009_prescriptionreview_approved_revision_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrescriptionProviderBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope_key", models.CharField(max_length=64, unique=True)),
                ("model_name", models.CharField(max_length=128)),
                ("window_started_at", models.DateTimeField()),
                ("requests_reserved", models.PositiveBigIntegerField(default=0)),
                ("token_units_reserved", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
