# Generated by Django 6.1.1 on 2026-09-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlcoholHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Alcohol History",
                "verbose_name_plural": "Alcohol Histories",
            },
        ),
        migrations.CreateModel(
            name="BloodGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CancerMarkerName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
                ("unit", models.CharField(blank=True, max_length=191)),
            ],
        ),
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comorbidity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Comorbidity",
                "verbose_name_plural": "Comorbidities",
            },
        ),
        migrations.CreateModel(
            name="CovidHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "COVID-19 History",
                "verbose_name_plural": "COVID-19 Histories",
            },
        ),
        migrations.CreateModel(
            name="DiagnosisDiseaseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosisLaterality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Diagnosis Laterality",
                "verbose_name_plural": "Diagnosis Lateralities",
            },
        ),
        migrations.CreateModel(
            name="DiagnosisMetastaticSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosisPrimarySite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiseaseProgressionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Disease Progression Status",
                "verbose_name_plural": "Disease Progression Status",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
            },
        ),
        migrations.CreateModel(
            name="EconomicStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Economic Status",
                "verbose_name_plural": "Economic Statuses",
            },
        ),
        migrations.CreateModel(
            name="HistopathologyDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Histopathology Details",
                "verbose_name_plural": "Histopathology Details",
            },
        ),
        migrations.CreateModel(
            name="HistopathologyGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistopathologySite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistopathologyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="IHCCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="IHCCycleResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="IHCStagingCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="IHCStagingCycleResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="IRECISTNewLesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "iRECIST New Lesion",
                "verbose_name_plural": "iRECIST New Lesions",
            },
        ),
        migrations.CreateModel(
            name="IRECISTNonTargetLesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "iRECIST Non-Target Lesion",
                "verbose_name_plural": "iRECIST Non-Target Lesions",
            },
        ),
        migrations.CreateModel(
            name="IRECISTResponseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "iRECIST Response Result",
                "verbose_name_plural": "iRECIST Response Results",
            },
        ),
        migrations.CreateModel(
            name="IRECISTTargetLesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "iRECIST Target Lesion",
                "verbose_name_plural": "iRECIST Target Lesions",
            },
        ),
        migrations.CreateModel(
            name="LineOfTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaritalStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Marital Status",
                "verbose_name_plural": "Marital Statuses",
            },
        ),
        migrations.CreateModel(
            name="MolecularPathologyGene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MolecularPathologyMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MolecularPathologyProteinMutation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MolecularPathologyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MolecularPathologySpecimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PathologicalResponseNewLesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Pathological Response New Lesion",
                "verbose_name_plural": "Pathological Response New Lesions",
            },
        ),
        migrations.CreateModel(
            name="PathologicalResponseNonTargetLesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Pathological Response Non-Target Lesion",
                "verbose_name_plural": "Pathological Response Non-Target Lesions",
            },
        ),
        migrations.CreateModel(
            name="PathologicalResponseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Pathological Response Result",
                "verbose_name_plural": "Pathological Response Results",
            },
        ),
        migrations.CreateModel(
            name="PathologicalResponseTargetLesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Pathological Response Target Lesion",
                "verbose_name_plural": "Pathological Response Target Lesions",
            },
        ),
        migrations.CreateModel(
            name="PatientType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Patient Type",
                "verbose_name_plural": "Patient Types",
            },
        ),
        migrations.CreateModel(
            name="ProgressionSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RadiotherapyIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RadiotherapyModality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Radiotherapy Modality",
                "verbose_name_plural": "Radiotherapy Modalities",
            },
        ),
        migrations.CreateModel(
            name="RadiotherapySite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RECISTNewLesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "RECIST 1.1 New Lesion",
                "verbose_name_plural": "RECIST 1.1 New Lesions",
            },
        ),
        migrations.CreateModel(
            name="RECISTNonTargetLesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "RECIST 1.1 Non-Target Lesion",
                "verbose_name_plural": "RECIST 1.1 Non-Target Lesions",
            },
        ),
        migrations.CreateModel(
            name="RECISTResponseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "RECIST 1.1 Response Result",
                "verbose_name_plural": "RECIST 1.1 Response Results",
            },
        ),
        migrations.CreateModel(
            name="RECISTTargetLesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "RECIST 1.1 Target Lesion",
                "verbose_name_plural": "RECIST 1.1 Target Lesions",
            },
        ),
        migrations.CreateModel(
            name="ResponseEstimationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Method of Estimation",
                "verbose_name_plural": "Methods of Estimation",
            },
        ),
        migrations.CreateModel(
            name="Sex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Sex",
                "verbose_name_plural": "Sex",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(default="Lungcancer Registry", max_length=120),
                ),
                (
                    "header_eyebrow",
                    models.CharField(default="Lung Cancer Registry", max_length=120),
                ),
                ("site_description", models.CharField(blank=True, max_length=255)),
                (
                    "logo",
                    models.FileField(blank=True, upload_to="site-branding/logos/"),
                ),
                (
                    "logo_alt_text",
                    models.CharField(
                        default="Lungcancer Registry logo", max_length=120
                    ),
                ),
                (
                    "favicon",
                    models.FileField(blank=True, upload_to="site-branding/favicons/"),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="SmokingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Smoking History",
                "verbose_name_plural": "Smoking Histories",
            },
        ),
        migrations.CreateModel(
            name="SurgeryLaterality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SurgeryModality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Surgery Modality",
                "verbose_name_plural": "Surgery Modalities",
            },
        ),
        migrations.CreateModel(
            name="SurvivalStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Survival Status",
                "verbose_name_plural": "Survival Status",
            },
        ),
        migrations.CreateModel(
            name="TBHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "TB History",
                "verbose_name_plural": "TB Histories",
            },
        ),
        migrations.CreateModel(
            name="TNMM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "TNM M",
                "verbose_name_plural": "TNM M",
            },
        ),
        migrations.CreateModel(
            name="TNMN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "TNM N",
                "verbose_name_plural": "TNM N",
            },
        ),
        migrations.CreateModel(
            name="TNMStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "TNM Stage",
                "verbose_name_plural": "TNM Stages",
            },
        ),
        migrations.CreateModel(
            name="TNMT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "TNM T",
                "verbose_name_plural": "TNM T",
            },
        ),
        migrations.CreateModel(
            name="TreatmentModality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
            options={
                "verbose_name": "Treatment Modality",
                "verbose_name_plural": "Treatment Modalities",
            },
        ),
        migrations.CreateModel(
            name="TreatmentProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="VaccinationDose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="IRECISTAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.irecistnewlesion",
                    ),
                ),
                (
                    "non_target_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.irecistnontargetlesion",
                    ),
                ),
                (
                    "response_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.irecistresponseresult",
                    ),
                ),
                (
                    "target_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.irecisttargetlesion",
                    ),
                ),
            ],
            options={
                "verbose_name": "iRECIST Assessment",
                "verbose_name_plural": "iRECIST Assessments",
            },
        ),
        migrations.CreateModel(
            name="MolecularPathologyExon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exons",
                        to="options.molecularpathologygene",
                    ),
                ),
            ],
            options={
                "unique_together": {("gene", "name")},
            },
        ),
        migrations.CreateModel(
            name="PathologicalResponseAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.pathologicalresponsenewlesion",
                    ),
                ),
                (
                    "non_target_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.pathologicalresponsenontargetlesion",
                    ),
                ),
                (
                    "response_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.pathologicalresponseresult",
                    ),
                ),
                (
                    "target_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.pathologicalresponsetargetlesion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathological Response Assessment",
                "verbose_name_plural": "Pathological Response Assessments",
            },
        ),
        migrations.CreateModel(
            name="RECIST11Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.recistnewlesion",
                    ),
                ),
                (
                    "non_target_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.recistnontargetlesion",
                    ),
                ),
                (
                    "response_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.recistresponseresult",
                    ),
                ),
                (
                    "target_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.recisttargetlesion",
                    ),
                ),
            ],
            options={
                "verbose_name": "RECIST 1.1 Assessment",
                "verbose_name_plural": "RECIST 1.1 Assessments",
            },
        ),
        migrations.CreateModel(
            name="TNMStagingPathological",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "m",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathological_m_staging",
                        to="options.tnmm",
                    ),
                ),
                (
                    "n",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathological_n_staging",
                        to="options.tnmn",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathological_stage_records",
                        to="options.tnmstage",
                    ),
                ),
                (
                    "t",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathological_t_staging",
                        to="options.tnmt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TNMStagingClinical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "m",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_m_staging",
                        to="options.tnmm",
                    ),
                ),
                (
                    "n",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_n_staging",
                        to="options.tnmn",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_stage_records",
                        to="options.tnmstage",
                    ),
                ),
                (
                    "t",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_t_staging",
                        to="options.tnmt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosisDiseaseSubgroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191)),
                (
                    "disease_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgroups",
                        to="options.diagnosisdiseasegroup",
                    ),
                ),
            ],
            options={
                "unique_together": {("disease_group", "name")},
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191)),
                ("degree", models.CharField(blank=True, max_length=250)),
                ("bmdc_number", models.CharField(blank=True, max_length=32)),
                ("institution", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("designation", models.CharField(blank=True, max_length=50)),
                ("department", models.CharField(blank=True, max_length=50)),
                ("photo", models.CharField(blank=True, max_length=55)),
                ("status", models.CharField(blank=True, max_length=10)),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctors",
                        to="options.center",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "bmdc_number", "institution"),
                        name="unique_doctor_identity",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MolecularPathologyMutation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191)),
                (
                    "exon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mutations",
                        to="options.molecularpathologyexon",
                    ),
                ),
            ],
            options={
                "unique_together": {("exon", "name")},
            },
        ),
        migrations.CreateModel(
            name="Thana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thanas",
                        to="options.district",
                    ),
                ),
            ],
            options={
                "unique_together": {("district", "name")},
            },
        ),
        migrations.CreateModel(
            name="TreatmentProtocolCycleNo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_no", models.PositiveIntegerField()),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="options.treatmentprotocol",
                    ),
                ),
            ],
            options={
                "unique_together": {("protocol", "cycle_no")},
            },
        ),
    ]
