# Generated by Django 6.1.1 on 2026-09-20 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tnmstagingpathological",
            name="m",
        ),
        migrations.RemoveField(
            model_name="tnmstagingpathological",
            name="n",
        ),
        migrations.RemoveField(
            model_name="tnmstagingpathological",
            name="stage",
        ),
        migrations.RemoveField(
            model_name="tnmstagingpathological",
            name="t",
        ),
        migrations.DeleteModel(
            name="TNMStagingClinical",
        ),
        migrations.DeleteModel(
            name="TNMStagingPathological",
        ),
    ]
