# Generated by Django 6.1.1 on 2026-09-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0002_remove_tnmstagingpathological_m_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MolecularAlterationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MolecularClinicalSignificance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MolecularPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
                ("manufacturer", models.CharField(blank=True, max_length=191)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="MolecularPanelTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coverage_notes", models.TextField(blank=True)),
                ("is_reportable", models.BooleanField(default=True)),
                (
                    "alteration_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.molecularalterationtype",
                    ),
                ),
                (
                    "covered_exons",
                    models.ManyToManyField(
                        blank=True,
                        related_name="panel_targets",
                        to="options.molecularpathologyexon",
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="panel_targets",
                        to="options.molecularpathologygene",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MolecularPanelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=100)),
                (
                    "reporting_policy",
                    models.CharField(
                        choices=[
                            ("explicit_only", "Explicit results only"),
                            (
                                "unreported_negative",
                                "Unreported covered targets are not detected",
                            ),
                            ("positives_only", "Positive findings only"),
                        ],
                        default="explicit_only",
                        max_length=30,
                    ),
                ),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.molecularpathologymethod",
                    ),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="options.molecularpanel",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="molecularpathologymutation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="molecularpathologymutation",
            name="exon",
        ),
        migrations.DeleteModel(
            name="MolecularPathologyProteinMutation",
        ),
        migrations.AddField(
            model_name="molecularpathologyresult",
            name="code",
            field=models.CharField(default="TEMP", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="molecularpathologyresult",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="molecularpaneltarget",
            name="panel_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="targets",
                to="options.molecularpanelversion",
            ),
        ),
        migrations.DeleteModel(
            name="MolecularPathologyMutation",
        ),
        migrations.AddConstraint(
            model_name="molecularpanelversion",
            constraint=models.UniqueConstraint(
                fields=("panel", "version"), name="unique_molecular_panel_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="molecularpaneltarget",
            constraint=models.UniqueConstraint(
                fields=("panel_version", "gene", "alteration_type"),
                name="unique_panel_gene_alteration",
            ),
        ),
    ]
