# Generated by Django 6.1.1 on 2026-09-21 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0003_molecularalterationtype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TreatmentProtocolDrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protocol_drugs",
                        to="options.treatmentdrug",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protocol_drugs",
                        to="options.treatmentprotocol",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "id"),
            },
        ),
        migrations.AddField(
            model_name="treatmentprotocol",
            name="drugs",
            field=models.ManyToManyField(
                related_name="protocols",
                through="options.TreatmentProtocolDrug",
                to="options.treatmentdrug",
            ),
        ),
        migrations.DeleteModel(
            name="TreatmentProtocolCycleNo",
        ),
        migrations.AddConstraint(
            model_name="treatmentprotocoldrug",
            constraint=models.UniqueConstraint(
                fields=("protocol", "drug"), name="unique_drug_per_protocol"
            ),
        ),
    ]
