# Generated by Django 6.1.1 on 2026-09-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0004_treatmentdrug_treatmentprotocoldrug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PathologicalResponseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TumorRegressionGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=191, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="pathologicalresponseassessment",
            name="new_lesion",
        ),
        migrations.RemoveField(
            model_name="pathologicalresponseassessment",
            name="non_target_lesion",
        ),
        migrations.RemoveField(
            model_name="pathologicalresponseassessment",
            name="response_result",
        ),
        migrations.RemoveField(
            model_name="pathologicalresponseassessment",
            name="target_lesion",
        ),
        migrations.RemoveField(
            model_name="recist11assessment",
            name="new_lesion",
        ),
        migrations.RemoveField(
            model_name="recist11assessment",
            name="non_target_lesion",
        ),
        migrations.RemoveField(
            model_name="recist11assessment",
            name="response_result",
        ),
        migrations.RemoveField(
            model_name="recist11assessment",
            name="target_lesion",
        ),
        migrations.DeleteModel(
            name="IRECISTAssessment",
        ),
        migrations.DeleteModel(
            name="PathologicalResponseNewLesion",
        ),
        migrations.DeleteModel(
            name="PathologicalResponseNonTargetLesion",
        ),
        migrations.DeleteModel(
            name="PathologicalResponseResult",
        ),
        migrations.DeleteModel(
            name="PathologicalResponseAssessment",
        ),
        migrations.DeleteModel(
            name="PathologicalResponseTargetLesion",
        ),
        migrations.DeleteModel(
            name="RECIST11Assessment",
        ),
    ]
