# Generated by Django 6.1.1 on 2026-09-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0005_pathologicalresponsecategory_tumorregressiongrade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseaseprogressionstatus",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="survivalstatus",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
