import type { PrescriptionDraftRecord } from "../../api";
import { draftTempId, type ObservationCollection } from "./draftWorkspace";

export type ObservationField = {
  key: string;
  label: string;
  type?: "text" | "number" | "date" | "datetime-local" | "textarea";
  resource?: string;
  required?: boolean;
  multiple?: boolean;
};

type CollectionSchema = { label: string; fields: readonly ObservationField[] };

export const observationFieldSchemas: Record<ObservationCollection, CollectionSchema> = {
  comorbidities: { label: "Comorbidities", fields: [{ key: "comorbidity", label: "Comorbidity", resource: "comorbidities", required: true }, { key: "diagnosed_on", label: "Diagnosed on", type: "date" }, { key: "notes", label: "Notes", type: "textarea" }] },
  diagnoses: { label: "Diagnosis", fields: [{ key: "disease_group", label: "Disease group", resource: "diagnosis-disease-groups", required: true }, { key: "disease_subgroup", label: "Disease subgroup", resource: "diagnosis-disease-subgroups" }, { key: "primary_site", label: "Primary site", resource: "diagnosis-primary-sites" }, { key: "laterality", label: "Laterality", resource: "diagnosis-lateralities" }, { key: "diagnosis_in_details", label: "Diagnosis details", type: "textarea" }, { key: "metastatic_sites", label: "Metastatic sites", resource: "progression-sites", multiple: true }] },
  histopathologies: { label: "Histopathology", fields: [{ key: "biopsy_date", label: "Biopsy date", type: "date" }, { key: "histopathology_details", label: "Histopathology details", resource: "histopathology-details" }, { key: "histopathology_type", label: "Histopathology type", resource: "histopathology-types" }, { key: "histopathology_site", label: "Histopathology site", resource: "histopathology-sites" }, { key: "histopathology_grade", label: "Histopathology grade", resource: "histopathology-grades" }, { key: "notes", label: "Notes", type: "textarea" }] },
  ihc_results: { label: "IHC results", fields: [{ key: "marker", label: "Marker", resource: "ihc-cycles", required: true }, { key: "reported_result", label: "Reported result", resource: "ihc-cycle-results", required: true }, { key: "tested_at", label: "Tested at", type: "date" }, { key: "notes", label: "Notes", type: "textarea" }] },
  pathological_staging_results: { label: "Pathological staging details", fields: [{ key: "feature", label: "Feature", resource: "ihc-staging-cycles", required: true }, { key: "result", label: "Result", resource: "ihc-staging-cycle-results", required: true }, { key: "tested_at", label: "Tested at", type: "date" }, { key: "notes", label: "Notes", type: "textarea" }] },
  clinical_tnm_stagings: { label: "Clinical TNM", fields: [{ key: "t", label: "T", resource: "tnm-t" }, { key: "n", label: "N", resource: "tnm-n" }, { key: "m", label: "M", resource: "tnm-m" }, { key: "stage", label: "Stage", resource: "tnm-stages" }, { key: "staged_at", label: "Staged at", type: "date" }, { key: "notes", label: "Notes", type: "textarea" }] },
  pathological_tnm_stagings: { label: "Pathological TNM", fields: [{ key: "t", label: "T", resource: "tnm-t" }, { key: "n", label: "N", resource: "tnm-n" }, { key: "m", label: "M", resource: "tnm-m" }, { key: "stage", label: "Stage", resource: "tnm-stages" }, { key: "staged_at", label: "Staged at", type: "date" }, { key: "notes", label: "Notes", type: "textarea" }] },
  molecular_tests: { label: "Molecular pathology", fields: [{ key: "panel", label: "Panel", resource: "molecular-panels" }, { key: "panel_version", label: "Panel version", resource: "molecular-panel-versions" }, { key: "method", label: "Method", resource: "molecular-methods" }, { key: "specimen", label: "Specimen", resource: "molecular-specimens" }, { key: "specimen_collected_on", label: "Specimen collected on", type: "date" }, { key: "tested_on", label: "Tested on", type: "date" }, { key: "reported_on", label: "Reported on", type: "date" }, { key: "qc_status", label: "QC status" }, { key: "gene", label: "Gene", resource: "molecular-genes" }, { key: "exon", label: "Exon", resource: "molecular-exons" }, { key: "alteration_type", label: "Alteration type", resource: "molecular-alteration-types" }, { key: "reported_result", label: "Reported result", resource: "molecular-results" }, { key: "clinical_significance", label: "Clinical significance", resource: "molecular-clinical-significances" }, { key: "dna_change", label: "DNA change" }, { key: "protein_change", label: "Protein change" }, { key: "common_name", label: "Common name" }, { key: "variant_allele_frequency", label: "Variant allele frequency", type: "number" }, { key: "copy_number", label: "Copy number", type: "number" }, { key: "laboratory", label: "Laboratory" }, { key: "accession_number", label: "Accession number" }, { key: "notes", label: "Notes", type: "textarea" }] },
  cancer_markers: { label: "Cancer markers", fields: [{ key: "marker_name", label: "Marker", resource: "cancer-marker-names", required: true }, { key: "marker_value", label: "Value", type: "number" }, { key: "unit", label: "Unit" }, { key: "tested_at", label: "Tested at", type: "date" }, { key: "notes", label: "Notes", type: "textarea" }] },
  treatments: { label: "Treatment protocols", fields: [{ key: "modality", label: "Modality", resource: "treatment-modalities" }, { key: "line_of_treatment", label: "Line of treatment", resource: "lines-of-treatment" }, { key: "protocol", label: "Protocol", resource: "treatment-protocols" }, { key: "protocol_cycle", label: "Protocol cycle" }, { key: "drug", label: "Drug", resource: "treatment-drugs" }, { key: "started_at", label: "Started at", type: "date" }, { key: "ended_at", label: "Ended at", type: "date" }, { key: "cycle_number", label: "Cycle number", type: "number" }, { key: "day_number", label: "Day number", type: "number" }, { key: "dose", label: "Dose", type: "number" }, { key: "dose_unit", label: "Dose unit" }, { key: "status", label: "Status" }, { key: "reason_for_stopping", label: "Reason for stopping" }, { key: "notes", label: "Notes", type: "textarea" }] },
  surgeries: { label: "Surgery", fields: [{ key: "modality", label: "Modality", resource: "surgery-modalities" }, { key: "laterality", label: "Laterality", resource: "surgery-lateralities" }, { key: "surgery_date", label: "Surgery date", type: "date" }, { key: "status", label: "Status" }, { key: "procedure_details", label: "Procedure details", type: "textarea" }, { key: "operative_findings", label: "Operative findings", type: "textarea" }, { key: "complications", label: "Complications", type: "textarea" }, { key: "notes", label: "Notes", type: "textarea" }] },
  radiotherapies: { label: "Radiotherapy", fields: [{ key: "site", label: "Site", resource: "radiotherapy-sites" }, { key: "intent", label: "Intent", resource: "radiotherapy-intents" }, { key: "modality", label: "Modality", resource: "radiotherapy-modalities" }, { key: "started_at", label: "Started at", type: "date" }, { key: "ended_at", label: "Ended at", type: "date" }, { key: "fraction_dose", label: "Fraction dose", type: "number" }, { key: "fraction_count", label: "Fraction count", type: "number" }, { key: "total_dose", label: "Total dose", type: "number" }, { key: "completed_fractions", label: "Completed fractions", type: "number" }, { key: "status", label: "Status" }, { key: "reason", label: "Reason" }, { key: "notes", label: "Notes", type: "textarea" }] },
  recist_assessments: { label: "RECIST", fields: [{ key: "assessed_at", label: "Assessed at", type: "date" }, { key: "target_lesion", label: "Target lesion", resource: "recist-target-lesions" }, { key: "non_target_lesion", label: "Non-target lesion", resource: "recist-non-target-lesions" }, { key: "new_lesion", label: "New lesion", resource: "recist-new-lesions" }, { key: "overall_response", label: "Overall response", resource: "recist-response-results" }, { key: "estimation_method", label: "Estimation method", resource: "response-estimation-methods" }, { key: "notes", label: "Notes", type: "textarea" }] },
  irecist_assessments: { label: "iRECIST", fields: [{ key: "assessed_at", label: "Assessed at", type: "date" }, { key: "target_lesion", label: "Target lesion", resource: "irecist-target-lesions" }, { key: "non_target_lesion", label: "Non-target lesion", resource: "irecist-non-target-lesions" }, { key: "new_lesion", label: "New lesion", resource: "irecist-new-lesions" }, { key: "overall_response", label: "Overall response", resource: "irecist-response-results" }, { key: "estimation_method", label: "Estimation method", resource: "response-estimation-methods" }, { key: "notes", label: "Notes", type: "textarea" }] },
  pathological_responses: { label: "Pathological response", fields: [{ key: "assessed_at", label: "Assessed at", type: "date" }, { key: "response_category", label: "Response category", resource: "pathological-response-categories" }, { key: "residual_viable_tumor_percent", label: "Residual viable tumor (%)", type: "number" }, { key: "tumor_regression_grade", label: "Tumor regression grade", resource: "tumor-regression-grades" }, { key: "estimation_method", label: "Estimation method", resource: "response-estimation-methods" }, { key: "notes", label: "Notes", type: "textarea" }] },
  progression_records: { label: "Disease progression", fields: [{ key: "status", label: "Status", resource: "disease-progression-statuses" }, { key: "assessed_on", label: "Assessed on", type: "date" }, { key: "progression_date", label: "Progression date", type: "date" }, { key: "progression_sites", label: "Progression sites", resource: "progression-sites", multiple: true }, { key: "estimation_method", label: "Estimation method", resource: "response-estimation-methods" }, { key: "notes", label: "Notes", type: "textarea" }] },
  survival_records: { label: "Survival follow-up", fields: [{ key: "status", label: "Status", resource: "survival-statuses" }, { key: "followed_up_on", label: "Followed up on", type: "date" }, { key: "death_date", label: "Death date", type: "date" }, { key: "cause_of_death", label: "Cause of death" }, { key: "notes", label: "Notes", type: "textarea" }] },
};

export function createBlankRecord(collection: ObservationCollection): PrescriptionDraftRecord {
  return {
    temp_id: draftTempId(collection),
    state: "edited",
    values: Object.fromEntries(observationFieldSchemas[collection].fields.map((field) => [field.key, field.multiple ? [] : ""])),
    resolutions: {},
    evidence_refs: [],
  };
}

function hasValue(value: unknown) {
  return Array.isArray(value) ? value.length > 0 : value !== undefined && value !== null && String(value).trim() !== "";
}

export function recordReady(collection: ObservationCollection, record: PrescriptionDraftRecord) {
  const requiredReady = observationFieldSchemas[collection].fields.filter((field) => field.required).every((field) => hasValue(record.values[field.key]));
  return requiredReady && Object.values(record.resolutions).every((resolution) => resolution.status === "resolved");
}
