# Generated by Django 6.1.1 on 2026-09-20 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("options", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observed_at", models.DateTimeField(blank=True, null=True)),
                ("prescription_date", models.DateField(blank=True, null=True)),
                (
                    "prescription_age_years",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "prescription_age_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "prescription_age_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("clinical_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("reviewed", "Reviewed"),
                            ("published", "Published"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_observations",
                        to="options.center",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clinical_observations",
                        to="options.doctor",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_clinical_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-observed_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Diagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosed_on", models.DateField(blank=True, null=True)),
                ("diagnosis_in_details", models.TextField(blank=True)),
                (
                    "disease_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.diagnosisdiseasegroup",
                    ),
                ),
                (
                    "disease_subgroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.diagnosisdiseasesubgroup",
                    ),
                ),
                (
                    "laterality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.diagnosislaterality",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "primary_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.diagnosisprimarysite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Histopathology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("biopsy_date", models.DateField(blank=True, null=True)),
                ("report_date", models.DateField(blank=True, null=True)),
                ("report_summary", models.TextField(blank=True)),
                (
                    "histopathology_details",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.histopathologydetails",
                    ),
                ),
                (
                    "histopathology_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.histopathologygrade",
                    ),
                ),
                (
                    "histopathology_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.histopathologysite",
                    ),
                ),
                (
                    "histopathology_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.histopathologytype",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histopathologies",
                        to="records.clinicalobservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetastaticSiteRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identified_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metastatic_sites",
                        to="records.diagnosis",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.diagnosismetastaticsite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_no", models.CharField(max_length=64, unique=True)),
                ("patient_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("nid", models.CharField(blank=True, max_length=50)),
                ("passport", models.CharField(blank=True, max_length=50)),
                ("photo", models.CharField(blank=True, max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                ("area", models.TextField(blank=True)),
                ("first_diagnosis_date", models.DateField(blank=True, null=True)),
                ("dietary_habits", models.TextField(blank=True, max_length=250)),
                (
                    "personal_history_of_cancer",
                    models.TextField(blank=True, max_length=250),
                ),
                (
                    "family_history_of_cancer",
                    models.TextField(blank=True, max_length=250),
                ),
                (
                    "cigarettes_per_day",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "smoking_duration_in_years",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "quit_smoking_for_in_years",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "pack_years",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=7,
                        null=True,
                    ),
                ),
                ("covid_infection_date", models.DateField(blank=True, null=True)),
                ("is_draft", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blood_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="options.bloodgroup",
                    ),
                ),
                (
                    "covid_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.covidhistory",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="options.district",
                    ),
                ),
                (
                    "economic_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="options.economicstatus",
                    ),
                ),
                (
                    "sex",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="options.sex",
                    ),
                ),
                (
                    "smoking_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.smokinghistory",
                    ),
                ),
                (
                    "tb_history",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.tbhistory",
                    ),
                ),
                (
                    "thana",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="options.thana",
                    ),
                ),
                (
                    "type_of_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="options.patienttype",
                    ),
                ),
                (
                    "vaccination_dose",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.vaccinationdose",
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.vaccine",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clinicalobservation",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="observations",
                to="records.patient",
            ),
        ),
        migrations.CreateModel(
            name="PatientAnthropometry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "bsa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "observation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anthropometry",
                        to="records.clinicalobservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientComorbidity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosed_on", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "comorbidity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.comorbidity",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comorbidities",
                        to="records.patient",
                    ),
                ),
            ],
        ),
    ]
