# Generated by Django 6.1.1 on 2026-09-20 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0001_initial"),
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="alcohol_history",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="options.alcoholhistory",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="any_known_mutation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="marital_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="options.maritalstatus",
            ),
        ),
    ]
