# Generated by Django 6.1.1 on 2026-09-20 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="clinicalobservation",
            new_name="obs_prescription_idx",
            old_name="obs_precription_idx",
        ),
    ]
