# Generated by Django 6.1.1 on 2026-09-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0002_remove_tnmstagingpathological_m_and_more"),
        ("records", "0002_rename_obs_precription_idx_obs_prescription_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalTNMStaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staged_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "m",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.tnmm",
                    ),
                ),
                (
                    "n",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.tnmn",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_tnm_stagings",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.tnmstage",
                    ),
                ),
                (
                    "t",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.tnmt",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["observation", "staged_on"],
                        name="clinical_tnm_obs_date_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IHCResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tested_at", models.DateField(blank=True, null=True)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "marker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.ihccycle",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ihc_results",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.ihccycleresult",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["observation", "tested_at"], name="ihc_obs_date_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("observation", "tested_at", "marker"),
                        name="unique_ihc_marker_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PathologicalStagingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessed_at", models.DateField(blank=True, null=True)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.ihcstagingcycle",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathological_staging_results",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.ihcstagingcycleresult",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["observation", "assessed_at"],
                        name="pathstage_obs_date_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("observation", "assessed_at", "feature"),
                        name="unique_pathstage_feature_date",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PathologicalTNMStaging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staged_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "m",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.tnmm",
                    ),
                ),
                (
                    "n",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.tnmn",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathological_tnm_stagings",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.tnmstage",
                    ),
                ),
                (
                    "t",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.tnmt",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["observation", "staged_on"],
                        name="path_tnm_obs_date_idx",
                    )
                ],
            },
        ),
    ]
