# Generated by Django 6.1.1 on 2026-09-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0003_molecularalterationtype_and_more"),
        ("records", "0003_clinicaltnmstaging_ihcresult_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MolecularTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specimen_collected_on", models.DateField(blank=True, null=True)),
                ("tested_on", models.DateField(blank=True, null=True)),
                ("reported_on", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "qc_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("partial", "Partially passed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("laboratory", models.CharField(blank=True, max_length=191)),
                ("accession_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.molecularpathologymethod",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="molecular_tests",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "panel_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tests",
                        to="options.molecularpanelversion",
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.molecularpathologyspecimen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MolecularTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dna_change", models.CharField(blank=True, max_length=191)),
                ("protein_change", models.CharField(blank=True, max_length=191)),
                ("common_name", models.CharField(blank=True, max_length=191)),
                (
                    "variant_allele_frequency",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "copy_number",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("explicit", "Explicitly reported"),
                            ("derived", "Automatically derived"),
                            ("manual", "Manually entered"),
                        ],
                        default="explicit",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "alteration_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.molecularalterationtype",
                    ),
                ),
                (
                    "clinical_significance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.molecularclinicalsignificance",
                    ),
                ),
                (
                    "exon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="test_results",
                        to="options.molecularpathologyexon",
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="test_results",
                        to="options.molecularpathologygene",
                    ),
                ),
                (
                    "molecular_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="records.moleculartest",
                    ),
                ),
                (
                    "panel_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="test_results",
                        to="options.molecularpaneltarget",
                    ),
                ),
                (
                    "partner_gene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fusion_partner_results",
                        to="options.molecularpathologygene",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.molecularpathologyresult",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="moleculartest",
            index=models.Index(
                fields=["observation", "reported_on"],
                name="molecular_test_obs_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moleculartest",
            index=models.Index(
                fields=["status", "qc_status"], name="molecular_test_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moleculartestresult",
            index=models.Index(
                fields=["molecular_test", "gene"], name="molecular_result_test_gene_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moleculartestresult",
            index=models.Index(
                fields=["gene", "result"], name="molecular_gene_result_idx"
            ),
        ),
    ]
