# Generated by Django 6.1.1 on 2026-09-21 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0004_treatmentdrug_treatmentprotocoldrug_and_more"),
        ("records", "0004_moleculartest_moleculartestresult_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_on", models.DateField(blank=True, null=True)),
                ("ended_on", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("stopped", "Stopped"),
                            ("held", "Held"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("reason_for_stopping", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "line_of_treatment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_courses",
                        to="options.lineoftreatment",
                    ),
                ),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_courses",
                        to="options.treatmentmodality",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_courses",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treatment_courses",
                        to="options.treatmentprotocol",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_on", "-id"),
            },
        ),
        migrations.CreateModel(
            name="TreatmentAdministration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("administered_on", models.DateField(blank=True, null=True)),
                (
                    "cycle_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("day_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "dose",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("dose_unit", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("given", "Given"),
                            ("delayed", "Delayed"),
                            ("held", "Held"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="administrations",
                        to="options.treatmentdrug",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_administrations",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "treatment_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrations",
                        to="records.treatmentcourse",
                    ),
                ),
            ],
            options={
                "ordering": ("-administered_on", "-id"),
            },
        ),
        migrations.CreateModel(
            name="CancerMarkerResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tested_on", models.DateField(blank=True, null=True)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "marker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="options.cancermarkername",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cancer_marker_results",
                        to="records.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ("-tested_on", "-id"),
                "indexes": [
                    models.Index(
                        fields=["observation", "tested_on"], name="cmarker_obs_date_idx"
                    ),
                    models.Index(
                        fields=["marker", "tested_on"], name="cmarker_marker_date_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("observation", "marker", "tested_on"),
                        name="unique_cmarker_obs_date",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="treatmentcourse",
            index=models.Index(
                fields=["observation", "started_on"], name="treatment_course_obs_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentcourse",
            index=models.Index(
                fields=["protocol", "status"], name="treatment_protocol_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentadministration",
            index=models.Index(
                fields=["treatment_course", "cycle_number"], name="treatment_cycle_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentadministration",
            index=models.Index(
                fields=["observation", "administered_on"],
                name="treatment_admin_obs_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentadministration",
            index=models.Index(
                fields=["drug", "administered_on"], name="treatment_drug_date_idx"
            ),
        ),
    ]
