# Generated by Django 6.1.1 on 2026-09-21 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0005_pathologicalresponsecategory_tumorregressiongrade_and_more"),
        ("records", "0005_treatmentcourse_treatmentadministration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IRECISTAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessed_on", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "estimation_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.responseestimationmethod",
                    ),
                ),
                (
                    "new_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.irecistnewlesion",
                    ),
                ),
                (
                    "non_target_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.irecistnontargetlesion",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irecist_assessments",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "overall_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.irecistresponseresult",
                    ),
                ),
                (
                    "target_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.irecisttargetlesion",
                    ),
                ),
                (
                    "treatment_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="irecist_assessments",
                        to="records.treatmentcourse",
                    ),
                ),
            ],
            options={
                "ordering": ("-assessed_on", "-id"),
            },
        ),
        migrations.CreateModel(
            name="PathologicalResponseAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessed_on", models.DateField()),
                (
                    "residual_viable_tumor_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "estimation_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.responseestimationmethod",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathological_response_assessments",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "response_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.pathologicalresponsecategory",
                    ),
                ),
                (
                    "treatment_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathological_response_assessments",
                        to="records.treatmentcourse",
                    ),
                ),
                (
                    "tumor_regression_grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.tumorregressiongrade",
                    ),
                ),
            ],
            options={
                "ordering": ("-assessed_on", "-id"),
            },
        ),
        migrations.CreateModel(
            name="RECIST11Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessed_on", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "estimation_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.responseestimationmethod",
                    ),
                ),
                (
                    "new_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.recistnewlesion",
                    ),
                ),
                (
                    "non_target_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.recistnontargetlesion",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recist11_assessments",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "overall_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.recistresponseresult",
                    ),
                ),
                (
                    "target_lesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.recisttargetlesion",
                    ),
                ),
                (
                    "treatment_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recist11_assessments",
                        to="records.treatmentcourse",
                    ),
                ),
            ],
            options={
                "ordering": ("-assessed_on", "-id"),
            },
        ),
        migrations.CreateModel(
            name="RadiotherapyCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_on", models.DateField(blank=True, null=True)),
                ("ended_on", models.DateField(blank=True, null=True)),
                (
                    "dose_per_fraction_cgy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "planned_fractions",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "completed_fractions",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "planned_total_dose_cgy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "delivered_total_dose_cgy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("stopped", "Stopped"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("reason_for_stopping", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "intent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="radiotherapy_courses",
                        to="options.radiotherapyintent",
                    ),
                ),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="radiotherapy_courses",
                        to="options.radiotherapymodality",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radiotherapy_courses",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="radiotherapy_courses",
                        to="options.radiotherapysite",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_on", "-id"),
                "indexes": [
                    models.Index(
                        fields=["observation", "started_on"],
                        name="radio_course_obs_idx",
                    ),
                    models.Index(
                        fields=["site", "intent"], name="radio_site_intent_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SurgeryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surgery_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("performed", "Performed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("procedure_details", models.TextField(blank=True)),
                ("operative_findings", models.TextField(blank=True)),
                ("complications", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "laterality",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgery_records",
                        to="options.surgerylaterality",
                    ),
                ),
                (
                    "modality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="surgery_records",
                        to="options.surgerymodality",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surgeries",
                        to="records.clinicalobservation",
                    ),
                ),
            ],
            options={
                "ordering": ("-surgery_date", "-id"),
                "indexes": [
                    models.Index(
                        fields=["observation", "surgery_date"],
                        name="surgery_obs_date_idx",
                    ),
                    models.Index(
                        fields=["modality", "surgery_date"], name="surgery_modality_idx"
                    ),
                ],
            },
        ),
    ]
