# Generated by Django 6.1.1 on 2026-09-21 14:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0005_pathologicalresponsecategory_tumorregressiongrade_and_more"),
        ("records", "0006_irecistassessment_pathologicalresponseassessment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="irecistassessment",
            name="confirmed_by",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirms_irecist_assessment",
                to="records.irecistassessment",
            ),
        ),
        migrations.AddField(
            model_name="irecistassessment",
            name="timepoint",
            field=models.CharField(
                choices=[
                    ("baseline", "Baseline"),
                    ("on_treatment", "On treatment"),
                    ("post_treatment", "Post treatment"),
                    ("confirmatory", "Confirmatory"),
                ],
                default="baseline",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pathologicalresponseassessment",
            name="timepoint",
            field=models.CharField(
                choices=[
                    ("baseline", "Baseline"),
                    ("on_treatment", "On treatment"),
                    ("post_treatment", "Post treatment"),
                    ("confirmatory", "Confirmatory"),
                ],
                default="post_treatment",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="recist11assessment",
            name="timepoint",
            field=models.CharField(
                choices=[
                    ("baseline", "Baseline"),
                    ("on_treatment", "On treatment"),
                    ("post_treatment", "Post treatment"),
                    ("confirmatory", "Confirmatory"),
                ],
                default="baseline",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pathologicalresponseassessment",
            name="residual_viable_tumor_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="irecistassessment",
            index=models.Index(
                fields=["observation", "assessed_on"], name="irecist_obs_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="irecistassessment",
            index=models.Index(
                fields=["treatment_course", "assessed_on"],
                name="irecist_course_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pathologicalresponseassessment",
            index=models.Index(
                fields=["observation", "assessed_on"], name="pathresp_obs_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pathologicalresponseassessment",
            index=models.Index(
                fields=["treatment_course", "assessed_on"],
                name="pathresp_course_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recist11assessment",
            index=models.Index(
                fields=["observation", "assessed_on"], name="recist_obs_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recist11assessment",
            index=models.Index(
                fields=["treatment_course", "assessed_on"],
                name="recist_course_date_idx",
            ),
        ),
    ]
