# Generated by Django 6.1.1 on 2026-09-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("options", "0006_diseaseprogressionstatus_code_survivalstatus_code"),
        ("records", "0007_irecistassessment_confirmed_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseProgressionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessed_on", models.DateField()),
                ("progression_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "estimation_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="options.responseestimationmethod",
                    ),
                ),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progression_records",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "progression_sites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="progression_records",
                        to="options.progressionsite",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progression_records",
                        to="options.diseaseprogressionstatus",
                    ),
                ),
                (
                    "treatment_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="progression_records",
                        to="records.treatmentcourse",
                    ),
                ),
            ],
            options={
                "ordering": ("-assessed_on", "-id"),
                "indexes": [
                    models.Index(
                        fields=["observation", "assessed_on"],
                        name="progression_obs_date_idx",
                    ),
                    models.Index(
                        fields=["treatment_course", "assessed_on"],
                        name="progression_course_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SurvivalFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("followed_up_on", models.DateField()),
                ("death_date", models.DateField(blank=True, null=True)),
                ("cause_of_death", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survival_followups",
                        to="records.clinicalobservation",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="followups",
                        to="options.survivalstatus",
                    ),
                ),
            ],
            options={
                "ordering": ("-followed_up_on", "-id"),
                "indexes": [
                    models.Index(
                        fields=["observation", "followed_up_on"],
                        name="survival_obs_date_idx",
                    ),
                    models.Index(
                        fields=["status", "followed_up_on"],
                        name="survival_status_date_idx",
                    ),
                ],
            },
        ),
    ]
